name: Pull request

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install protoc
        uses: arduino/setup-protoc@master
      - name: Install protoc-gen-grpc-web protoc plugin
        run: |
          sudo wget https://github.com/grpc/grpc-web/releases/download/1.1.0/protoc-gen-grpc-web-1.1.0-linux-x86_64 -O /usr/local/bin/protoc-gen-grpc-web
          sudo chmod a+x /usr/local/bin/protoc-gen-grpc-web
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Test
        run: |
          npm run test:generate
          npm run test:generate-grpc-web
          npm run test
